### ISSUE TITLE
Sidebar gets wider with every reload

### ISSUE THREAD

**Issue by jacobwgillespie** [drcika/apc-extension#75]
Hi! It appears that when using a right sidebar arrangement and moving the activity bar to the bottom or top, every reload of VS Code makes the sidebar a little bit wider.

My settings are:

```json
{
  "apc.activityBar": {
    "hideSettings": true,
    "position": "bottom",
    "size": 32
  },
  "apc.electron": {
    "titleBarStyle": "hiddenInset"
  },
  "workbench.sideBar.location": "right"
}
```

**Comment by jacobwgillespie** [comment]
Hey! 👋 I believe this was fixed with v0.3.1, but that version never got published to the VS Code extension marketplace. Would you be able to publish it? Thanks!

**Comment by drcika** [comment]
0.3.1 will be with vscode 1.83
this problem should have been solved with 0.3.0

**Comment by jacobwgillespie** [comment]
Ah interesting, so I'm still having this problem and actually started having it with v0.3.0 (I thought v0.3.1 was the fix). 

I think the original issue #65 was about the sidebar getting smaller on each reload, though I didn't have that original issue and now the sidebar is getting larger. Not sure if this is because I have a right-aligned sidebar or if something else is causing it.

**Comment by drcika** [comment]
https://github.com/drcika/apc-extension/assets/35919606/626df32d-7d6c-42e1-8237-f774f59f320e

**Comment by jacobwgillespie** [comment]
I wonder if it's because my main sidebar is on the right:


https://github.com/drcika/apc-extension/assets/130874/420eb9e8-5806-4124-a1e9-9272b62a4f97
